# pi-issue-runner 設定ファイル
# 詳細: https://github.com/takemo101/pi-issue-runner/blob/main/docs/configuration.md

# =====================================
# Worktree設定
# =====================================
worktree:
  # worktreeの作成先ディレクトリ
  base_dir: ".worktrees"

  # デフォルトのベースブランチ（--base オプションで上書き可能）
  base_branch: "origin/main"

  # worktree作成時にコピーするファイル
  copy_files:
    - .env
    - .env.local
    - .envrc

  # worktree作成時にコピーするディレクトリ（再帰コピー）
  copy_dirs:
    - .opencode

# =====================================
# マルチプレクサ設定
# =====================================
multiplexer:
  # 使用するマルチプレクサ: tmux | zellij
  type: "tmux"

  # セッション名のプレフィックス（例: pi-issue-42）
  session_prefix: "pi"

  # セッション内で起動するか
  start_in_session: true

# =====================================
# エージェント設定
# =====================================
agent:
  # エージェントタイプ: pi | claude | opencode | custom
  type: "pi"

  # エージェントに渡す追加引数
  args:
    - --provider
    - kimi-coding
    - --model
    - k2p5

# =====================================
# GitHub設定
# =====================================
github:
  # Issueのコメントをプロンプトに含める
  include_comments: true

  # 最大コメント数（0 = 無制限）
  max_comments: 10

# =====================================
# 並列実行設定
# =====================================
parallel:
  # 同時実行数の上限（0 = 無制限）
  max_concurrent: 5

# =====================================
# auto ワークフロー選択設定
# =====================================
auto:
  provider: kimi-coding
  model: k2p5

# =====================================
# 複数ワークフロー定義
# -w 省略時は auto（AIがIssue内容から自動選択）
# =====================================
workflows:
  # 標準: 計画→実装→レビュー→マージ
  default:
    description: 標準ワークフロー（計画・実装・レビュー・マージ）
    steps:
      - plan:
          context: |
            実装計画を作成してください。
            複雑な場合は designer エージェントに委譲してください：
            ```javascript
            subagent({ agent: "designer", task: "実装設計を作成" })
            ```
      - implement:
          context: |
            実装を行ってください。
            
            複数ファイルを作成する場合は並列実行：
            ```javascript
            subagent({
              tasks: [
                { agent: "implementer", task: "[ファイル1] を作成" },
                { agent: "implementer", task: "[ファイル2] を作成" }
              ]
            })
            ```
            
            品質チェックも並列実行：
            ```javascript
            subagent({
              tasks: [
                { agent: "tester", task: "ShellCheckとテストを実行" },
                { agent: "reviewer", task: "コードレビュー" }
              ]
            })
            ```
      - review:
          context: |
            コードレビューを行い、10点満点でスコアリングしてください。
            
            ## 評価基準
            - コード品質（4点）: ShellCheck準拠、エラーハンドリング、可読性
            - テスト（3点）: カバレッジ、エッジケース、信頼性
            - 設計整合性（3点）: Issue要件充足、既存コードとの整合性
            
            ## レビュープロセス
            ```javascript
            subagent({
              tasks: [
                { agent: "reviewer", task: "コード品質チェック" },
                { agent: "reviewer", task: "テスト評価" },
                { agent: "reviewer", task: "設計整合性評価" }
              ]
            })
            ```
            
            ## 判定基準
            - **9-10点**: APPROVE → 次のステップへ進む
            - **6-8点**: REQUEST_CHANGES → fixer エージェントで修正
              ```javascript
              subagent({ agent: "fixer", task: "レビュー指摘を修正" })
              ```
              修正後、再度レビュー（実装ステップに戻る）
            - **5点以下**: MAJOR_REVISION → 設計からやり直し
              実装ステップに戻って再実装
            
            必ず最終スコアを出力してください：
            ```
            ## レビュースコア: X/10
            - コード品質: X/4
            - テスト: X/3
            - 設計整合性: X/3
            
            判定: [APPROVE/REQUEST_CHANGES/MAJOR_REVISION]
            ```
      - merge

  # 機能追加: 計画→実装→レビュー→マージ
  feature:
    description: 新機能・大規模変更（lib/scripts への新関数追加、新スクリプト作成）
    steps:
      - plan:
          context: |
            実装計画を作成してください。
            複雑な場合は designer エージェントに委譲：
            ```javascript
            subagent({ agent: "designer", task: "実装設計を作成" })
            ```
      - implement:
          context: |
            新機能を実装してください。
            
            複数ファイルは並列作成：
            ```javascript
            subagent({
              tasks: [
                { agent: "implementer", task: "lib/xxx.sh を作成" },
                { agent: "implementer", task: "lib/yyy.sh を作成" },
                { agent: "implementer", task: "scripts/zzz.sh を作成" },
                { agent: "tester", task: "テストファイルを作成" }
              ]
            })
            ```
            
            品質チェック（並列）：
            ```javascript
            subagent({
              tasks: [
                { agent: "tester", task: "ShellCheck実行" },
                { agent: "tester", task: "Batsテスト実行" },
                { agent: "reviewer", task: "セルフレビュー" }
              ]
            })
            ```
            
            ドキュメント更新：
            ```javascript
            subagent({ agent: "librarian", task: "AGENTS.mdを更新" })
            ```
      - review:
          context: |
            コードレビューを行い、10点満点でスコアリングしてください。
            
            ## 評価基準
            - コード品質（4点）: ShellCheck準拠、エラーハンドリング、可読性
            - テスト（3点）: カバレッジ、エッジケース、信頼性
            - 設計整合性（3点）: Issue要件充足、既存コードとの整合性
            
            ## 判定基準
            - **9-10点**: APPROVE → 次のステップへ
            - **6-8点**: fixer で修正 → 再レビュー
            - **5点以下**: 設計からやり直し
            
            出力形式:
            ```
            ## レビュースコア: X/10
            判定: [APPROVE/REQUEST_CHANGES/MAJOR_REVISION]
            ```
      - merge
    context: |
      ## 技術スタック
      - Bash 4.0+ / ShellCheck 準拠
      - テスト: Bats (Bash Automated Testing System)
      - YAML: yq + フォールバック簡易パーサー (lib/yaml.sh)

      ## 方針
      - 全ファイルに `set -euo pipefail` を設定
      - 関数は小文字スネークケース、ローカル変数は `local` 宣言

  # バグ修正・リファクタリング
  fix:
    description: バグ修正・リファクタリング・セキュリティ修正
    steps:
      - implement:
          context: |
            バグ修正・リファクタリングを行ってください。
            
            修正前に影響範囲を確認：
            ```javascript
            subagent({ agent: "explorer", task: "変更の影響範囲を調査" })
            ```
            
            修正後の検証（並列）：
            ```javascript
            subagent({
              tasks: [
                { agent: "tester", task: "ShellCheck実行" },
                { agent: "tester", task: "Batsテスト実行" }
              ]
            })
            ```
      - review:
          context: |
            コードレビューを行い、10点満点でスコアリングしてください。
            
            ## 評価基準
            - コード品質（4点）: ShellCheck準拠、エラーハンドリング、可読性
            - テスト（3点）: カバレッジ、エッジケース、信頼性
            - 設計整合性（3点）: Issue要件充足、既存コードとの整合性
            
            ## 判定基準
            - **9-10点**: APPROVE → 次のステップへ
            - **6-8点**: fixer で修正 → 再レビュー
            - **5点以下**: 設計からやり直し
            
            出力形式:
            ```
            ## レビュースコア: X/10
            判定: [APPROVE/REQUEST_CHANGES/MAJOR_REVISION]
            ```
      - merge
    context: |
      ## 方針
      - 修正範囲を最小限に抑える
      - 回帰テストの追加を検討
      - ShellCheck 警告を解消
      - 既存機能の後方互換性を維持

  # ドキュメント: 実装→マージ（軽量モデルで十分）
  docs:
    description: ドキュメント更新（README, AGENTS.md, docs/ 以下）
    steps:
      - implement:
          context: |
            ドキュメントを更新してください。
            完了後、librarian エージェントで最終確認：
            ```javascript
            subagent({ agent: "librarian", task: "ドキュメント整合性を確認" })
            ```
      - merge

  # テスト追加: 実装→レビュー→マージ
  test:
    description: テスト追加・テスト改善
    steps:
      - implement:
          context: |
            テストを追加・改善してください。
            tester エージェントを使用：
            ```javascript
            subagent({
              tasks: [
                { agent: "tester", task: "ユニットテストを作成" },
                { agent: "tester", task: "統合テストを作成" },
                { agent: "tester", task: "全テストを実行して検証" }
              ]
            })
            ```
      - review:
          context: |
            コードレビューを行い、10点満点でスコアリングしてください。
            
            ## 評価基準
            - コード品質（4点）: ShellCheck準拠、エラーハンドリング、可読性
            - テスト（3点）: カバレッジ、エッジケース、信頼性
            - 設計整合性（3点）: Issue要件充足、既存コードとの整合性
            
            ## 判定基準
            - **9-10点**: APPROVE → 次のステップへ
            - **6-8点**: fixer で修正 → 再レビュー
            - **5点以下**: 設計からやり直し
            
            出力形式:
            ```
            ## レビュースコア: X/10
            判定: [APPROVE/REQUEST_CHANGES/MAJOR_REVISION]
            ```
      - merge

  # 簡易修正: 実装→マージのみ（軽微な変更）
  quickfix:
    description: typo修正・設定値変更・コメント修正など軽微な変更
    steps:
      - implement
      - merge

  # シンプル: 実装→マージ（テストなし、最速）
  simple:
    description: 最もシンプルなワークフロー（実装のみ）
    steps:
      - implement
      - merge

# =====================================
# 計画書設定
# =====================================
plans:
  # 保持する計画書の件数（0 = 全て保持）
  keep_recent: 10

  # 計画書ディレクトリ
  dir: "docs/plans"

# =====================================
# improve 設定
# =====================================
improve:
  # カスタムレビュープロンプトファイル
  review_prompt_file: "agents/improve-review.md"

  # ログ設定
  logs:
    keep_recent: 10
    keep_days: 7
    dir: ".improve-logs"

# =====================================
# Hook設定
# =====================================
hooks:
  # インラインコマンドの実行を許可（デフォルト: false）
  allow_inline: true

  # 成功時の通知
  on_success: |
    osascript -e 'display notification "Issue #'"$PI_ISSUE_NUMBER"' が完了しました" with title "Pi Issue Runner" subtitle "✅ 完了" sound name "Glass"'

  # エラー時の通知
  on_error: |
    osascript -e 'display notification "'"$PI_ERROR_MESSAGE"'" with title "Pi Issue Runner" subtitle "❌ Issue #'"$PI_ISSUE_NUMBER"' エラー" sound name "Basso"'

  # セッション開始時
  on_start: |
    osascript -e 'display notification "Issue #'"$PI_ISSUE_NUMBER"' を開始しました" with title "Pi Issue Runner" subtitle "🚀 開始" sound name "Pop"'

  # クリーンアップ後
  on_cleanup: |
    echo "Cleanup completed for Issue #$PI_ISSUE_NUMBER"

  # improve開始時
  on_improve_start: |
    osascript -e 'display notification "改善ループを開始します（最大 '"$PI_MAX_ITERATIONS"' 回）" with title "Pi Issue Runner" subtitle "🔄 improve開始" sound name "Pop"'

  # improve終了時
  on_improve_end: |
    osascript -e 'display notification "改善ループ完了: 作成 '"$PI_ISSUES_CREATED"' / 成功 '"$PI_ISSUES_SUCCEEDED"' / 失敗 '"$PI_ISSUES_FAILED"'" with title "Pi Issue Runner" subtitle "🏁 improve終了" sound name "Glass"'

  # イテレーション開始時
  on_iteration_start: |
    osascript -e 'display notification "イテレーション '"$PI_ITERATION"'/'"$PI_MAX_ITERATIONS"' を開始" with title "Pi Issue Runner" subtitle "🔁 イテレーション開始" sound name "Pop"'

  # イテレーション終了時
  on_iteration_end: |
    osascript -e 'display notification "イテレーション '"$PI_ITERATION"'/'"$PI_MAX_ITERATIONS"' 完了: 成功 '"$PI_ISSUES_SUCCEEDED"' / 失敗 '"$PI_ISSUES_FAILED"'" with title "Pi Issue Runner" subtitle "✅ イテレーション終了" sound name "Purr"'

  # レビュー完了時
  on_review_complete: |
    osascript -e 'display notification "レビュー完了: '"$PI_REVIEW_ISSUES_COUNT"' 件の問題を発見" with title "Pi Issue Runner" subtitle "🔍 レビュー完了" sound name "Tink"'

# =====================================
# Watcher設定
# =====================================
watcher:
  # PRマージタイムアウト時に強制クリーンアップ
  force_cleanup_on_timeout: true

  # エラー検知時にターミナルを自動で開いてセッションにアタッチする
  auto_attach: false
