# Default workflow for GitHub issue processing
# Template variables: {{issue_number}}, {{issue_title}}, {{branch_name}}, {{worktree_path}}
name: default
description: 完全なワークフロー（計画・実装・レビュー・マージ）
steps:
  - plan
  - implement
  - review
  - merge
context: |
  ## ワークフローの方針
  - 計画を立ててから実装を行う
  - 実装後は必ずレビューを実施
  - テストを追加・更新する
  - コミットメッセージは明確に記述する
