# Default workflow for GitHub issue processing
# Template variables: {{issue_number}}, {{issue_title}}, {{branch_name}}, {{worktree_path}}
name: default
description: 標準ワークフロー（計画・実装・テスト・レビュー・マージ）
steps:
  - plan
  - implement
  - test
  - review
  - merge
context: |
  ## ワークフローの方針
  - 計画を立ててから実装を行う
  - テストは全テストスイートを実行し、既存機能の破壊がないことを確認する
  - レビューでは変更の波及影響を重点的に確認する
  - コミットメッセージは明確に記述する
